# Generated by Django 5.1.7 on 2025-03-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户id')),
                ('username', models.CharField(blank=True, max_length=10, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=18, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
    ]
