# Generated by Django 5.1.7 on 2025-03-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
