# Generated by Django 5.1.7 on 2025-03-13 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish_date'], 'verbose_name': '文章'},
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
